version: "3.5"
services:
  mongodb:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    networks:
      - backend

  server:
    container_name: web_server
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_PATH=src
      - DB_HOST=mongo
      - DB=dbdb
    networks:
      - backend
    depends_on:
      - mongodb

networks:
  backend:
    driver: bridge

volumes:
  mongo: